# Generated by Django 6.0.4 on 2026-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('buy', 'Покупка'), ('rent', 'Аренда')], default='buy', max_length=10, verbose_name='Тип заявки')),
                ('name', models.CharField(max_length=100, verbose_name='Имя контакта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Название компании')),
                ('activity_type', models.CharField(blank=True, max_length=100, verbose_name='Вид деятельности')),
                ('property_type', models.CharField(max_length=100, verbose_name='Что ищет (Офис/Склад/др.)')),
                ('location', models.CharField(max_length=200, verbose_name='Желаемое место/район')),
                ('area_required', models.CharField(max_length=100, verbose_name='Желаемая площадь')),
                ('budget', models.IntegerField(verbose_name='Бюджет (до)')),
                ('floor_pref', models.CharField(blank=True, max_length=50, verbose_name='Желаемый этаж')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('manager', models.CharField(max_length=100, verbose_name='Менеджер')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('active', 'В работе'), ('closed', 'Закрыт')], default='new', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=10, verbose_name='Тип сделки')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Имя (Владелец/Контакт)')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес объекта')),
                ('area', models.FloatField(verbose_name='Площадь (м2)')),
                ('price', models.IntegerField(verbose_name='Стоимость (Общая)')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('total_floors', models.IntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('levels', models.IntegerField(default=1, verbose_name='Кол-во уровней')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('manager', models.CharField(max_length=100, verbose_name='Менеджер')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('active', 'В работе'), ('deal', 'Сделка'), ('archive', 'Архив')], default='active', max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
