# Generated by Django 6.0.4 on 2026-04-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('actual', 'Актуально'), ('not_actual', 'Неактуально')], default='actual', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('actual', 'Актуально'), ('not_actual', 'Неактуально')], default='actual', max_length=20, verbose_name='Статус'),
        ),
    ]
