# Generated by Django 6.0.4 on 2026-04-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_status_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='client',
            name='area_required',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Желаемая площадь'),
        ),
        migrations.AlterField(
            model_name='client',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бюджет (до)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='client',
            name='floor_pref',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Желаемый этаж'),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Желаемое место/район'),
        ),
        migrations.AlterField(
            model_name='client',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя контакта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Что ищет'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь (м2)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='levels',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Кол-во уровней'),
        ),
        migrations.AlterField(
            model_name='property',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя (Владелец/Контакт)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость (Общая)'),
        ),
    ]
