# Generated by Django 6.0.4 on 2026-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_client_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Всего этажей'),
        ),
    ]
