# Generated by Django 6.0.4 on 2026-04-16 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_property_floor_alter_property_total_floors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='manager_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='property',
            name='manager_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Менеджер (Текст)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Менеджер (Текст)'),
        ),
    ]
