# Generated by Django 6.0.4 on 2026-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_client_manager_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата актуализации'),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата актуализации'),
        ),
    ]
